//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_VaccineVer6.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BenhNhan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BenhNhan()
        {
            this.OutputIfs = new HashSet<OutputIf>();
        }
    
        public string IdBn { get; set; }
        public string HoTen { get; set; }
        public string Phone { get; set; }
        public string DiaChi { get; set; }
        public Nullable<System.DateTime> NgayTiem { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutputIf> OutputIfs { get; set; }
    }
}
