//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_VaccineVer6.Model
{
    using QL_VaccineVer6.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class BenhNhan : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BenhNhan()
        {
            this.OutputIfs = new HashSet<OutputIf>();
        }
        private string _IdBn;
        public string IdBn { get => _IdBn; set { _IdBn = value; OnPropertyChanged(); } }
        private string _HoTen;
        public string HoTen { get => _HoTen; set { _HoTen = value; OnPropertyChanged(); } }
        private string _Phone;
        public string Phone { get => _Phone; set { _Phone = value; OnPropertyChanged(); } }
        private string _Diachi;
        public string DiaChi { get => _Diachi; set { _Diachi = value; OnPropertyChanged(); } }
        private Nullable<System.DateTime> _NgayTiem;
        public Nullable<System.DateTime> NgayTiem { get => _NgayTiem; set { _NgayTiem = value; OnPropertyChanged(); } }

        private string _IdVac;
        public string IdVac { get => _IdVac; set { _IdVac = value; OnPropertyChanged(); } }

        private Vaccine _Vaccine;
        public virtual Vaccine Vaccine
        {
            get => _Vaccine; set { _Vaccine = value; OnPropertyChanged(); }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutputIf> OutputIfs { get; set; }
    }
}
