//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_VaccineVer6.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InputIf
    {
        public string IdInputIf { get; set; }
        public string IdInput { get; set; }
        public string IdVac { get; set; }
        public Nullable<int> Soluong { get; set; }
        public Nullable<double> IntputPrice { get; set; }
        public Nullable<double> OutputPrice { get; set; }
    
        //Su dung dc cac thong so can thiet cho relationship cua entity
        public virtual Input Input { get; set; }
        public virtual Vaccine Vaccine { get; set; }
    }
}
