//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_VaccineVer6.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_VaccineEntities : DbContext
    {
        public QL_VaccineEntities()
            : base("name=QL_VaccineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BenhNhan> BenhNhans { get; set; }
        public virtual DbSet<Input> Inputs { get; set; }
        public virtual DbSet<InputIf> InputIfs { get; set; }
        public virtual DbSet<NhacungCap> NhacungCaps { get; set; }
        public virtual DbSet<Output> Outputs { get; set; }
        public virtual DbSet<OutputIf> OutputIfs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Vaccine> Vaccines { get; set; }
    }
}
