//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_VaccineVer6.Model
{
    using QL_VaccineVer6.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class NhacungCap :BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhacungCap()
        {
            this.Vaccines = new HashSet<Vaccine>();
        }

        private String _TenNcc;
        public int IdNcc { get; set; }
        public string TenNcc { get => _TenNcc; set { _TenNcc = value;OnPropertyChanged(); }  }
        public string Adress { get; set; }
        public string Phone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vaccine> Vaccines { get; set; }
    }
}
