//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_VaccineVer6.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutputIf
    {
        public string IdOutIf { get; set; }
        public string IdVac { get; set; }
        public Nullable<int> Soluong { get; set; }
        public string IdBn { get; set; }
        public string IdOutput { get; set; }
    
        public virtual BenhNhan BenhNhan { get; set; }
        public virtual Output Output { get; set; }
        public virtual Vaccine Vaccine { get; set; }
    }
}
